# inspired by http://geekyplatypus.com/making-your-dockerised-php-application-even-better/
version: '3'
services:
  elastic:
    build: pledari-elastic
    ports:
      - "9200:9200"
      - "9300:9300"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
  phpfpm:
    image: php:7-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - ./www:/app